name: Hello world action
description: Action that passes 'world' as a parameter
inputs:
  who-to-greet:
    description: Who to greet
    required: true
    default: World-cust-action
outputs:
  time: 'The time we greeted-cust'
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.who-to-greet }}
