name: Day 2 1
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to where to deploy
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps: [run: echo 'Building⋯']
  test:
    runs-on: ubuntu-latest
    needs: build
    steps: [run: echo '👷🏽Testing⋯']
  load-test:
    runs-on: ubuntu-latest
    needs: test
    steps: 
      run: |
        echo '👟Testing⋯'
        echo sleep 1
    production:
      if: github.event.inputs.environment == 'Production'
      runs-on: ubuntu-latest
      needs: [test, load-test]
      steps: 
        run: |
          echo '1️⃣Deploying⋯'
          echo '2️⃣Deploying⋯'
          echo '3️⃣Deploying⋯'
          echo '4️⃣Deploying⋯'
          echo '5️⃣Deployed✔︎'
