name: reusable-workflow
on:
  workflow_call:
    inputs:
      who-to-greet:
        type: string
        required: true
        default: World-reus
    outputs:
      time-3t:
      value: "${{ jobs.reusable-job.outputs.time-2 }}"
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    outputs:
      time: ${{ steps.generate-output-time.outputs.time-from-run }}
      time-2: some time 2
    steps:
      - id: generate-output-time
        run: echo "::set-output name=time-from-run::$(date)"
