---
name: reuse-top
on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        type: string
        required: true
        default: World-reus
jobs:
  call-workflow:
  #note invalid value workflow reference: cannot specify version when calling local workflows
  #. https://github.com/RUBenGAMArrarodRiguEZ-ToMtOm/actions-fundamentals/actions/runs/3089637623
    uses: ./.github/workflows/reusable.yml
    with:
       who-to-greet: ${{ github.actor }}
  use-output:
    runs-on: ubuntu-latest
    needs: call-workflow
    #steps: [run: echo "${{ needs.call-workflow.outputs.time }}"]
    steps: [run: echo 'sample text']
...
